### ISSUE TITLE
Refactor interactions metrics

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#426]
Right now interactions with accounts metric is triggered when sending a transaction, but interaction can come from other sources.

We should refactor the account metric and add other network metrics in the ingestion of events. There we can digest a lot of information from what is going on on the network.

**Comment by illia-malachyn** [comment]
I'm encountering the same problem while working on `gather fees metric on both Flow and EVM side`. We must do that in the `event ingestion` rather than the `requester` module to also track interactions coming from other sources. However, we don't have enough information in the event ingestion engine for this metric. We index only `EVM.TransactionExecuted` and `EVM.BlockExecuted` events although I need `FlowFees.FeesDeducted` event to gather fees on the Flow side. I can extend the engine to track this event too but it raises the question of the gateway's responsibility - whether this is an appropriate place to gather this metric.
