### ISSUE TITLE
Internal error while sending eth_getStorageAt

### ISSUE THREAD

**Issue by AntonieDavid** [onflow/flow-evm-gateway#660]
## Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

When sending this ` {"jsonrpc": "2.0", "method": "eth_getStorageAt", "id": 659307, "params": ["0x2a03a891add2dc6d0f7b94419086630ba5cb65b6", "0x0", "latest"]}`  payload to evm-gw paired with the public AN endpoint, it works, but when we send the request to evm-gw connected to our own local AN, the req fails with internal error. This seems to be an isolated case, since many other tested methods work fine in the latter setup.

Using default access node running configs (provided in the setup instructions) and similar for evm-gateway with the exception of the following parameter: `--init-cadence-height=211176670`

### Steps to Reproduce 

Send curl req with the above payload to a node running with that specific cadence height when spinned up.

**Comment by m-Peter** [comment]
Hey @AntonieDavid, thanks for reporting 🙏
For this to work with a local AN, the execution data API should be enabled, as far as I know.
For the public ANs, this is already enabled, that's why it works.
In the near future, couple of weeks, we will roll out some changes, and the `eth_getStorageAt` will be powered by the EVM Gateway's local state index, without the need to get the necessary data from an AN.

**Comment by vishalchangrani** [comment]
hey @m-Peter - @AntonieDavid has enabled execution data API on the Access node but still runs into the same issue.
Anything else he could check?
